# Generated by Django 5.1.1 on 2025-04-09 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_contact_managers'),
        ('app', '0002_alter_contact_photo'),
    ]

    operations = [
    ]
